import en from '@vueform/vueform/locales/en'

import {
  // accepted,
  // active_url,
  // after,
  // after_or_equal,
  // alpha,
  // alpha_dash,
  // alpha_num,
  // array,
  // before,
  // before_or_equal,
  // between,
  // boolean,
  // captcha,
  // completed,
  // confirmed,
  // date,
  // date_equals,
  // date_format,
  // different,
  // digits,
  // digits_between,
  // dimensions,
  // distinct,
  // email,
  // exists,
  // file,
  // filled,
  // gt,
  // gte,
  // image,
  // in_,
  // in_array,
  // integer,
  // ip,
  // ipv4,
  // ipv6,
  // json,
  // lt,
  // lte,
  // max,
  // mimes,
  // mimetypes,
  // min,
  // not_in,
  // not_regex,
  // nullable,
  // numeric,
  // regex,
  required,
  // same,
  // size,
  // string,
  // timezone,
  // unique,
  // url,
  // uuid,
  defineConfig,
} from './vueform.core'

import {
  // Mandatory form components
  Vueform,
  FormElements,
  
  // Essential form components (optional)
  FormErrors,
  FormMessages,

  // Essential element components (optional)
  ElementLayout,
  ElementLayoutInline,
  ElementLoader,
  ElementLabelFloating,
  ElementLabel,
  ElementInfo,
  ElementDescription,
  ElementError,
  ElementMessage,
  ElementText,
  ElementAddon,
  ElementAddonOptions,

  // Optional form components (optional)
  FormLanguages,
  FormLanguage,
  FormTabs,
  FormTab,
  FormSteps,
  FormStepsControls,
  FormStepsControl,
  FormStep,

  // Elements (optional)
  ButtonElement,
  CaptchaElement,
  CheckboxElement,
  CheckboxgroupElement,
  DateElement,
  DatesElement,
  FileElement,
  GroupElement,
  HiddenElement,
  ListElement,
  LocationElement,
  MultifileElement,
  MultiselectElement,
  ObjectElement,
  PhoneElement,
  RadioElement,
  RadiogroupElement,
  SelectElement,
  SliderElement,
  StaticElement,
  TagsElement,
  TextareaElement,
  TextElement,
  ToggleElement,
  EditorElement,
  TTextareaElement,
  TTextElement,
  TEditorElement,

  // Element partials & wrappers (optional)
  DragAndDrop,
  CheckboxgroupCheckbox,
  RadiogroupRadio,
  FilePreview,
  DatepickerWrapper,
  EditorWrapper,

  // Alternative views (optional)
  CheckboxgroupElement_tabs,
  CheckboxgroupElement_blocks,
  CheckboxgroupCheckbox_tabs,
  CheckboxgroupCheckbox_blocks,
  FilePreview_image,
  FilePreview_gallery,
  RadiogroupRadio_tabs,
  RadiogroupRadio_blocks,
  RadiogroupElement_tabs,
  RadiogroupElement_blocks,
  
  // Mandatory imports
  classes,
  columns,
} from '@vueform/vueform/themes/tailwind'

// create our own theme
const tailwind = {
  templates: {
    // Mandatory form components
    Vueform,
    FormElements,
    
    // Essential form components (optional)
    FormErrors,
    FormMessages,

    // Essential element components (optional)
    ElementLayout,
    ElementLayoutInline,
    ElementLoader,
    ElementLabelFloating,
    ElementLabel,
    ElementInfo,
    ElementDescription,
    ElementError,
    ElementMessage,
    ElementText,
    ElementAddon,
    ElementAddonOptions,

    // Optional form components (optional)
    // FormLanguages,
    // FormLanguage,
    // FormTabs,
    // FormTab,
    // FormSteps,
    // FormStepsControls,
    // FormStepsControl,
    // FormStep,

    // Elements
    ButtonElement,
    // CaptchaElement,
    CheckboxElement,
    CheckboxgroupElement,
    // DateElement,
    // DatesElement,
    // FileElement,
    // GroupElement,
    // HiddenElement,
    // ListElement,
    // LocationElement,
    // MultifileElement,
    // MultiselectElement,
    // ObjectElement,
    PhoneElement,
    RadioElement,
    RadiogroupElement,
    SelectElement,
    // SliderElement,
    // StaticElement,
    // TagsElement,
    // TextareaElement,
    TextElement,
    ToggleElement,
    // EditorElement,
    // TTextareaElement,
    // TTextElement,
    // TEditorElement,

    // Element partials & wrappers
    // DragAndDrop,
    CheckboxgroupCheckbox,
    RadiogroupRadio,
    // FilePreview,
    // DatepickerWrapper,
    // EditorWrapper,

    // Alternative views (optional)
    // CheckboxgroupElement_tabs,
    // CheckboxgroupElement_blocks,
    // CheckboxgroupCheckbox_tabs,
    // CheckboxgroupCheckbox_blocks,
    // FilePreview_image,
    // FilePreview_gallery,
    // RadiogroupRadio_tabs,
    // RadiogroupRadio_blocks,
    // RadiogroupElement_tabs,
    // RadiogroupElement_blocks,
  },

  // Include these
  classes,
  columns,
}


export default defineConfig({
  locales: { en },
  locale: 'en',
  theme: tailwind,
  rules: {
    // accepted,
    // active_url,
    // after,
    // after_or_equal,
    // alpha,
    // alpha_dash,
    // alpha_num,
    // array,
    // before,
    // before_or_equal,
    // between,
    // boolean,
    // captcha,
    // completed,
    // confirmed,
    // date,
    // date_equals,
    // date_format,
    // different,
    // digits,
    // digits_between,
    // dimensions,
    // distinct,
    // email,
    // exists,
    // file,
    // filled,
    // gt,
    // gte,
    // image,
    // in: in_,
    // in_array,
    // integer,
    // ip,
    // ipv4,
    // ipv6,
    // json,
    // lt,
    // lte,
    // max,
    // mimes,
    // mimetypes,
    // min,
    // not_in,
    // not_regex,
    // nullable,
    // numeric,
    // regex,
    required,
    // same,
    // size,
    // string,
    // timezone,
    // unique,
    // url,
    // uuid,
  }
  // ...
})